/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f0xx.h"

int main(void)
{
	volatile uint32_t i;
	uint8_t pole[32] = {1,0,1,0,1,0,0,1,1,1,0,1,1,1,0,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0};

	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER5_0;
	GPIOA->BSRR = (1<<5); // set
	i=0;

        while (1) {
        	if (pole[i] == 1) {GPIOA->BSRR = (1<<5);}
        	if (pole[i] == 0) {GPIOA->BRR = (1<<5);}
        	i++;
        	if (i >= sizeof(pole)) i=0;

        	for (volatile uint32_t i = 0; i < 100000; i++) {}

	    }
}
